spring.application.name=RestaurantSystem

# JWT
jwt.secret=restaurant-system-secret-key-must-be-at-least-256-bits-long
jwt.expiration=86400000

# Perfil ativo
spring.profiles.active=dev
spring.jpa.open-in-view=false
